experiment_name: "cvpr_seq60"

data:
  train_anno_dir: "/media/SSD/data/CVPR_workshop/annotation/ABAW Annotations/ABAW Annotations/EXPR_Recognition_Challenge/Train_Set"
  val_anno_dir: "/media/SSD/data/CVPR_workshop/annotation/ABAW Annotations/ABAW Annotations/EXPR_Recognition_Challenge/Validation_Set"
  image_base_dirs:
    - "/media/SSD/data/CVPR_workshop/cropped_aligned_image/image"
  audio_dir: "/media/SSD/data/CVPR_workshop/audio"
  seq_len: 60
  stride: 15
  image_size: 224
  fps: 30
  audio_sample_rate: 16000
  num_classes: 8

loader:
  batch_size: 32
  num_workers: 8

optim:
  grad_accum_steps: 2
  epochs: 30
  learning_rate: 1.0e-5

checkpoint:
  dir: "/home/dong/Emotion_Project/code/cvpr/checkpoints/seq60"
  best_name: "best_model_vgcmf.pth"

log:
  dir: "/home/dong/Emotion_Project/code/cvpr/logs/seq60"
  filename: "train.log"
  summary_filename: "metrics.txt"
